title: "SpamEDGE Company"
description: "SpamEDGE Company delivers precision-driven solutions in geospatial technology, surveying, engineering, construction, architecture, and digital innovation."

url: "https://spamedgecompany.github.io"
baseurl: ""

lang: "en"

author:
  name: "SpamEDGE Company"

logo: "/favicon.png"

social:
  name: "SpamEDGE Company"
  links: []

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

twitter:
  card: summary_large_image
